// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRatingSystem.Repository.DB;

namespace MovieRatingSystem.Repository.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210609182509_RenameToContent")]
    partial class RenameToContent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.Actor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.Content", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.ContentActor", b =>
                {
                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("ContentID")
                        .HasColumnType("int");

                    b.HasKey("ActorID", "ContentID");

                    b.HasIndex("ContentID");

                    b.ToTable("content_actor");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.ContentRating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContentID")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContentID");

                    b.ToTable("ContentRating");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.ContentActor", b =>
                {
                    b.HasOne("MovieRatingSystem.Shared.DB.Actor", "Actor")
                        .WithMany("ActorContent")
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRatingSystem.Shared.DB.Content", "Content")
                        .WithMany("ContentActors")
                        .HasForeignKey("ContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.ContentRating", b =>
                {
                    b.HasOne("MovieRatingSystem.Shared.DB.Content", "Content")
                        .WithMany("Ratings")
                        .HasForeignKey("ContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.Actor", b =>
                {
                    b.Navigation("ActorContent");
                });

            modelBuilder.Entity("MovieRatingSystem.Shared.DB.Content", b =>
                {
                    b.Navigation("ContentActors");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
